name: Reportar problema
description: "Olá! Por favor preenche este formulário para que possamos resolver o teu problema"
title: "Insere um título para o teu problema"
labels: ["bug"]
body:
  - type: input
    id: email
    attributes:
      label: Identificar conta
      description: Por favor indica o email associado à tua conta na aplicação (email associado ao fénix)
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Onde foi?
      description: Insere o link da página onde isto aconteceu
      placeholder: https://
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: O que aconteceu?
      description: Descreve mais detalhadamente o problema
      placeholder: "ex. quando carrego no botão de upload aparece uma mensagem a dizer 401 - Unauthorized"
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: Em que browser estás a usar a app?
      multiple: false
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Outro
  - type: markdown
    attributes:
      value: "## Já temos tudo, obrigado pelo teu contributo!"
  - type: markdown
    attributes:
      value: "### Carrega no botão que está no final deste formulário para submeteres o teu report"
